set -euo pipefail
OV="${1:-}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOG="$ROOT/test-artifacts"
mkdir -p "$LOG"
echo "[pipeline] start OV=$OV" | tee -a "$LOG/pipeline.log"
bash -x "$ROOT/scripts/overlay_with_logging.sh" "$OV" | tee "$LOG/overlay.$(date +%s).log"
bash -x "$ROOT/scripts/run_all_tests.sh"        | tee "$LOG/run.$(date +%s).log"
bash -x "$ROOT/scripts/publish_public.sh"       | tee "$LOG/publish.$(date +%s).log"
bash -x "$ROOT/scripts/verify_public.sh"        | tee "$LOG/verify.$(date +%s).log"
echo "[pipeline] done" | tee -a "$LOG/pipeline.log"
